### ISSUE TITLE
cached response incomplete

### ISSUE THREAD

**Issue by gauteh** [valeriansaliou/bloom#15]
Hi, I am getting clipped responses when set up with nginx. First request looks good (using curl), but second gets part of the response clipped (typically last bit of </html>), docker-compose:

```
version: '3'

services:
  redis:
    image: redis
    restart: always

  dars:
    build: ../..
    volumes:
      - ../../data:/data:ro


  bloom:
    image: valeriansaliou/bloom:v1.28.0
    depends_on:
      - redis
      - dars
    volumes:
      - ./bloom-config.cfg:/etc/bloom.cfg:ro

  nginx:
    image: nginx
    depends_on:
      - bloom
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx:ro
```

ref: https://github.com/gauteh/dars/pull/9
